<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-6PU7QPRN" failures="3" tests="3" name="Default test" time="14.158" errors="0" timestamp="26 Feb 2022 13:44:49 GMT">
  <testcase classname="data_driven.Login_User" name="login_userdata" time="0.945">
    <failure type="java.lang.AssertionError" message="success expected [[[ChromeDriver: chrome on WINDOWS (07567b5e028b6b35cfd503d7c4417e4c)] -&amp;gt; xpath: (//input[@name=&amp;apos;search&amp;apos;])[1]]] but found [[[ChromeDriver: chrome on WINDOWS (07567b5e028b6b35cfd503d7c4417e4c)] -&amp;gt; xpath: //a[contains(text(),&amp;apos;iPhone&amp;apos;)]]]">
      <![CDATA[java.lang.AssertionError: success expected [[[ChromeDriver: chrome on WINDOWS (07567b5e028b6b35cfd503d7c4417e4c)] -> xpath: (//input[@name='search'])[1]]] but found [[[ChromeDriver: chrome on WINDOWS (07567b5e028b6b35cfd503d7c4417e4c)] -> xpath: //a[contains(text(),'iPhone')]]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at data_driven.Login_User.validation_of_product(Login_User.java:76)
at data_driven.Login_User.login_userdata(Login_User.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login_userdata -->
  <testcase classname="data_driven.Login_User" name="login_userdata" time="1.018">
    <failure type="java.lang.AssertionError" message="success expected [[[ChromeDriver: chrome on WINDOWS (84b912619ccfb903b6480de0ace470d1)] -&amp;gt; xpath: (//input[@name=&amp;apos;search&amp;apos;])[1]]] but found [[[ChromeDriver: chrome on WINDOWS (84b912619ccfb903b6480de0ace470d1)] -&amp;gt; xpath: //a[contains(text(),&amp;apos;iPhone&amp;apos;)]]]">
      <![CDATA[java.lang.AssertionError: success expected [[[ChromeDriver: chrome on WINDOWS (84b912619ccfb903b6480de0ace470d1)] -> xpath: (//input[@name='search'])[1]]] but found [[[ChromeDriver: chrome on WINDOWS (84b912619ccfb903b6480de0ace470d1)] -> xpath: //a[contains(text(),'iPhone')]]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at data_driven.Login_User.validation_of_product(Login_User.java:76)
at data_driven.Login_User.login_userdata(Login_User.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login_userdata -->
  <testcase classname="data_driven.Login_User" name="login_userdata" time="1.027">
    <failure type="java.lang.AssertionError" message="success expected [[[ChromeDriver: chrome on WINDOWS (7ab21a4eaab14f189a8f1beb59099f9c)] -&amp;gt; xpath: (//input[@name=&amp;apos;search&amp;apos;])[1]]] but found [[[ChromeDriver: chrome on WINDOWS (7ab21a4eaab14f189a8f1beb59099f9c)] -&amp;gt; xpath: //a[contains(text(),&amp;apos;iPhone&amp;apos;)]]]">
      <![CDATA[java.lang.AssertionError: success expected [[[ChromeDriver: chrome on WINDOWS (7ab21a4eaab14f189a8f1beb59099f9c)] -> xpath: (//input[@name='search'])[1]]] but found [[[ChromeDriver: chrome on WINDOWS (7ab21a4eaab14f189a8f1beb59099f9c)] -> xpath: //a[contains(text(),'iPhone')]]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at data_driven.Login_User.validation_of_product(Login_User.java:76)
at data_driven.Login_User.login_userdata(Login_User.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login_userdata -->
</testsuite> <!-- Default test -->
